#!/usr/bin/python
import socket

HOST = '0.0.0.0' 
PORT = 5003

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind((HOST, PORT))
    s.listen()
    conn, addr = s.accept()
    with conn:
        data = conn.recv(1024)
        conn.sendall(str(conn.getpeername()).encode("utf-8"))
print("fin")
